spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      url: ${REDIS_URL}

  liquibase:
    enabled: true

app:
  jwt:
    secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    com.dway: INFO
    root: WARN